language: scala
scala:
  - 2.12.6

services:
  - docker

script:
  - sbt coverage test coverageReport

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
    - "$HOME/.sbt/launchers/"
    - "$HOME/.coursier"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7c0be6cfe54ee6cdb7c4
    on_success: always
    on_failure: always
    on_start: never

deploy:
  skip_cleanup: true
  provider: script
  script: sbt docker:publish
#  on:
#    tags: true
#    condition: $TRAVIS_PULL_REQUEST = false
